# -*- coding: utf-8 -*-

# addons_path = "$HOME/.oryon/addons"

[log]
log_level = "DEBUG"

[db]
dsn = "user:password@tcp(127.0.0.1:3306)/hello"
connMaxLifetime = 0
maxIdleConns = 10
maxOpenConns = 100

[service]
addr = "0.0.0.0"
port = 9528
enabledTLS = false
tlsCertFile = ""
tlsKeyFile = ""
tlscaFile = ""
tlsServerName = ""